
spring:
  cloud:
    gateway:
      routes:
      - id: redirectRoute
        uri: http://172.17.22.126:9081/getname
        predicates:
        - Path=/path
        filters:
        - name: RequestRateLimiter
          args:
            key-resolver: "#{@defaultKeyResolver}"
            redis-rate-limiter.replenishRate: 100
            redis-rate-limiter.burstCapacity: 100
#         - name: RequestRateLimiter
#           args:
#             key-resolver: "#{@newResolver}"
#             redis-rate-limiter.replenishRate: 1
#             redis-rate-limiter.burstCapacity: 1      
        - name: Hystrix
          args:
            name: fallbackcmd
            fallbackUri: forward:/fallback
      - id: HeaderMatching
        uri: http://localhost:9080/world
        predicates:
        - Path=/header
        - Header=X-Request-Id, \d+
        filters:
        - name: RequestRateLimiter
          args:
            key-resolver: "#{@searchKeyResolver}"
            redis-rate-limiter.replenishRate: 10
            redis-rate-limiter.burstCapacity: 10
      - id: HystrixExample
        uri: http://localhost:9081/getname
        predicates:
        - Path=/checkingfallback
        filters:
        - name: Hystrix
          args:
            name: fallbackcmd
            fallbackUri: forward:/world
      - id: MethodMatching
        uri: http://localhost:9080/world
        predicates:
        - Path=/post
        - Method=POST
      - id: dummypath
        uri: http://localhost:9080/world
        predicates:
        - Path=/dummy
