
spring:
  cloud:
    gateway:
      routes:
      - id: properties_route1
        uri: http://localhost:9081/getname
        predicates:
        - Path=/foo/
      - id: properties_route2
        uri: http://localhost:9081/getname
        predicates:
        - Path=/foor/
