
spring:
  cloud:
    gateway:
      routes:
      - id: properties_route1
        uri: http://localhost:9081/getname
        predicates:
        - Path=/foo/
      -id: route-2
        uri: http://localhost:9081/getname
         predicates:
         - Path=/foor/
