
spring:
  cloud:
    gateway:
      routes:
      - id: redirectRoute
        uri: http://localhost:9081/getname
        predicates:
        - Path=/foo/
      - id: HeaderMatching
        uri: http://localhost:9080/world
        predicates:
        - Header=X-Request-Id, \d+
      -id: HystrixExample
        uri: https://localhost:9080/getname
        predicates:
        - Path=/consumingserviceendpoint
        filters:
        - name: Hystrix
          args:
            name: fallbackcmd
            fallbackUri: forward:/fallback
            
