
spring:
  cloud:
    gateway:
      routes:
      - id: redirectRoute
        uri: http://localhost:9081/getname
        predicates:
        - Path=/foo
      - id: HeaderMatching
        uri: http://localhost:9080/world
        predicates:
        -Path=/post
        -Method=POST
      -id: HystrixExample
        uri: https://localhost:9080/getname
        predicates:
        - Path=/get
        filters:
        - name: Hystrix
          args:
            name: fallbackcmd
            fallbackUri: forward:/fallback
            
