
spring:
  cloud:
    gateway:
      routes:
      - id: redirectRoute
        uri: http://localhost:9081/getname
        predicates:
        - Path=/four
      - id: HeaderMatching
        uri: http://localhost:9080/world
        predicates:
        - Path=/post
        - Header=X-Request-Id, \d+
      - id: HystrixExample
        uri: http://localhost:9081/getname
        predicates:
        - Path=/getmyname
        filters:
        - name: Hystrix
          args:
            name: fallbackcmd
            fallbackUri: forward:/world
            
