
spring:
  cloud:
    gateway:
      routes:
      - id: redirectRoute
        uri: http://localhost:9081/getname
        predicates:
        - Path=/path
        filters:
        - RequestRateLimiter=100, 100, #{@testKeyResolver}
      - id: HeaderMatching
        uri: http://localhost:9080/world
        predicates:
        - Path=/header
        - Header=X-Request-Id, \d+
      - id: HystrixExample
        uri: http://localhost:9081/getname
        predicates:
        - Path=/checkfallback
        filters:
        - name: Hystrix
          args:
            name: fallbackcmd
            fallbackUri: forward:/world
      - id: HeaderMatching
        uri: http://localhost:9080/world
        predicates:
        - Path=/post
        - Method=POST
